ntf_app:
  name: sample_sme_app # required
  ntf_type: sme # required
  shared_key: fhlaskjdh_falkjqwerkn # optional - shared/or public-private
  public_key: asdfadsfalsdkfalsdkjfh # optional
  private_key: qqpweorqiueypzcnvfadf # optional
  geneve_field_id: 0x5384 # required
  token_insert: geneve # default
  granularity: packet # default
  match:
    label: frontend
    label: production
  default: deny # default
  on_success: allow # default
